import { initHeaderCondense, initVideoCards, initSmoothScroll, initReveals, initParallax, initScrollProgress } from './effects.js';
import { initCounters } from './counters.js';
import { initEnrollForm } from './whatsapp.js';
import { initAurora } from './aurora.js';
import { initScrub } from './scrub.js';
initAurora();
initSmoothScroll();
initReveals();
initParallax();
initScrollProgress();
initHeaderCondense();
initVideoCards();
initCounters();
initEnrollForm();
initScrub();
